"use client"
import MainNavBar from "@/components/MainNavBar"
import "./globals.css"
import { Inter } from "next/font/google"
import MainFooter from "@/components/MainFooter"
import { ThemeProvider } from "next-themes"

const inter = Inter({ subsets: ["latin"] })

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// }

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
     
			<body className={inter.className}>
				<ThemeProvider defaultTheme="light" disableTransitionOnChange   attribute='class'>
      
					<MainNavBar />
					{children}
					<MainFooter />
				</ThemeProvider>
			</body>
		</html>
	)
}
