import MainNavBar from '@/components/MainNavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import MainFooter from '@/components/MainFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainNavBar />
        {children}
        <MainFooter />
        </body>
    </html>
  )
}
